version: "3"

services:
  test_db:
    image: postgres:15.1
    volumes:
      - ylab_test_db:/var/lib/postgresql/data
    env_file:
      - .env_test
    ports:
      - "5432:5432"
    networks:
      - ylab_test-network
    container_name: ylab_test-db
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  test_api:
    build: .
    command: bash start_tests.sh
    volumes:
      - ./:/app/
    env_file:
      - .env_test
    ports:
      - "8000:8000"
    networks:
      - ylab_test-network
    depends_on:
      test_db:
        condition: service_healthy
      test_redis:
        condition: service_healthy
    container_name: ylab_test-api

  test_redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_test_storage:/data
    networks:
      - ylab_test-network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    container_name: ylab_test-redis

networks:
  ylab_test-network:

volumes:
  ylab_test_db:
  redis_test_storage:
