version: "3"

services:
  db:
    image: postgres:16.0
    volumes:
      - ylab_db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - ylab-network
    container_name: ylab-db

  back:
    build: .
    command: bash start_app.sh
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    networks:
      - ylab-network
    depends_on:
      - db
    container_name: ylab-back
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_storage:/data
    networks:
      - ylab-network

    container_name: ylab-redis


networks:
  ylab-network:

volumes:
  ylab_db:
  redis_storage:
