version: "3"

services:
  test_db:
    image: postgres:16.0
    volumes:
      - ylab_test_db:/var/lib/postgresql/data
    env_file:
      - .env_test
    ports:
      - "5432:5432"
    networks:
      - ylab_test-network
    container_name: ylab_test-db

  test_api:
    build: .
    command: bash start_tests.sh
    volumes:
      - ./:/app/
    env_file:
      - .env_test
    ports:
      - "8000:8000"
    networks:
      - ylab_test-network
    depends_on:
      - test_db
    container_name: ylab_test-api

networks:
  ylab_test-network:

volumes:
  ylab_test_db:
