"""Добавить возможность удаления дочернего элемента при удалении родительского

Revision ID: 1b6a38c950db
Revises: 49d0a16e68a0
Create Date: 2024-01-22 11:03:20.075232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6a38c950db'
down_revision: Union[str, None] = '49d0a16e68a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
