"""Добавить возможность удаления дочернего элемента при удалении родительского

Revision ID: 49d0a16e68a0
Revises: 6339b5d17c24
Create Date: 2024-01-22 11:02:12.037472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d0a16e68a0'
down_revision: Union[str, None] = '6339b5d17c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
