"""Добавить поля для количества блюд и сабменю в родительских моделях

Revision ID: 50cf3dd1c576
Revises: 171b202f3d2b
Create Date: 2024-01-22 11:39:42.313330

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '50cf3dd1c576'
down_revision: str | None = '171b202f3d2b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('submenus_count', sa.Integer(), nullable=False))
    op.add_column('menu', sa.Column('dishes_count', sa.Integer(), nullable=False))
    op.add_column('submenu', sa.Column('dishes_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submenu', 'dishes_count')
    op.drop_column('menu', 'dishes_count')
    op.drop_column('menu', 'submenus_count')
    # ### end Alembic commands ###
