"""Обновить дефолтное значение колонки id и отношения между таблицами

Revision ID: 6339b5d17c24
Revises: 727853d11c80
Create Date: 2024-01-22 10:52:03.130121

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = '6339b5d17c24'
down_revision: str | None = '727853d11c80'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
