"""Обновить дефолтное значение колонки id и отношения между таблицами

Revision ID: 6339b5d17c24
Revises: 727853d11c80
Create Date: 2024-01-22 10:52:03.130121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6339b5d17c24'
down_revision: Union[str, None] = '727853d11c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
