"""Заменить тип данных id заменить на uuid

Revision ID: 7ee187d8839f
Revises: 94f860f918ef
Create Date: 2024-01-21 12:34:04.748626

"""
from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7ee187d8839f'
down_revision: str | None = '94f860f918ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'id',
                    existing_type=sa.String(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    # ### end Alembic commands ###
