"""Добавить автоматическое подтягивание количества блюд у сабменю

Revision ID: e574adcba516
Revises: 3d1909705403
Create Date: 2024-01-28 09:29:27.094603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e574adcba516'
down_revision: Union[str, None] = '3d1909705403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submenu', 'dishes_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('dishes_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
