"""init relationsheeps

Revision ID: 712914fff8f7
Revises:
Create Date: 2024-02-11 12:34:17.641656

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = '712914fff8f7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
